



<?php

$items = array(
        #sample	array("id" => "1", "name" => "nice stone", "stackable" => "1"),
        #sample	array("id" => "4", "name" => "gobble stone")

	array("id" => "0", "name" => "air", "stackable" => "1"), 
	array("id" => "1", "name" => "stone", "stackable" => "1"), 
	array("id" => "2", "name" => "grass", "stackable" => "1"), 
	array("id" => "3", "name" => "dirt", "stackable" => "1"), 
	array("id" => "4", "name" => "cobblestone", "stackable" => "1"), 
	array("id" => "5", "name" => "wooden plank", "stackable" => "1"), 
	array("id" => "6", "name" => "sapling", "stackable" => "1"), 
	array("id" => "7", "name" => "bedrock", "stackable" => "1"), 
	array("id" => "8", "name" => "water", "stackable" => "1"), 
	array("id" => "9", "name" => "stationnary water", "stackable" => "1"), 
	array("id" => "10", "name" => "lava", "stackable" => "1"), 
	array("id" => "11", "name" => "stationnary lava", "stackable" => "1"), 
	array("id" => "12", "name" => "sand", "stackable" => "1"), 
	array("id" => "13", "name" => "gravel", "stackable" => "1"), 
	array("id" => "14", "name" => "gold ore", "stackable" => "1"), 
	array("id" => "15", "name" => "iron ore", "stackable" => "1"), 
	array("id" => "16", "name" => "coal ore", "stackable" => "1"), 
	array("id" => "17", "name" => "wood", "stackable" => "1"), 
	array("id" => "18", "name" => "leaves", "stackable" => "1"), 
	array("id" => "19", "name" => "sponge", "stackable" => "1"), 
	array("id" => "20", "name" => "glass", "stackable" => "1"), 
	array("id" => "21", "name" => "lapis lazuli ore", "stackable" => "1"), 
	array("id" => "22", "name" => "dispenser", "stackable" => "1"), 
	array("id" => "23", "name" => "sandstone", "stackable" => "1"), 
	array("id" => "24", "name" => "note block", "stackable" => "1"), 
	array("id" => "25", "name" => "note block", "stackable" => "1"), 
#	array("id" => "26", "name" => "bed", "stackable" => "1"), 
	array("id" => "27", "name" => "powered rail", "stackable" => "1"), 
	array("id" => "28", "name" => "detector rail", "stackable" => "1"), 
	array("id" => "29", "name" => "sticky piston", "stackable" => "1"), 
	array("id" => "30", "name" => "cobweb", "stackable" => "1"), 
	array("id" => "31", "name" => "tall grass", "stackable" => "1"), 
	array("id" => "32", "name" => "dead bush", "stackable" => "1"), 
	array("id" => "33", "name" => "piston", "stackable" => "1"), 
	array("id" => "34", "name" => "piston extension", "stackable" => "1"), 
	array("id" => "35", "name" => "wool", "stackable" => "1"), 
	array("id" => "36", "name" => "block moved by piston", "stackable" => "1"), 
	array("id" => "37", "name" => "yellow flower", "stackable" => "1"), 
	array("id" => "38", "name" => "red rose", "stackable" => "1"), 
	array("id" => "39", "name" => "brown mushroom", "stackable" => "1"), 
	array("id" => "40", "name" => "red mushroom", "stackable" => "1"), 
	array("id" => "41", "name" => "gold block", "stackable" => "1"), 
	array("id" => "42", "name" => "iron block", "stackable" => "1"), 
	array("id" => "43", "name" => "double stone stab", "stackable" => "1"), 
	array("id" => "44", "name" => "stone stab", "stackable" => "1"), 
	array("id" => "45", "name" => "brick block", "stackable" => "1"), 
	array("id" => "46", "name" => "tnt", "stackable" => "1"), 
	array("id" => "47", "name" => "bookshelf", "stackable" => "1"), 
	array("id" => "48", "name" => "moss stone", "stackable" => "1"), 
	array("id" => "49", "name" => "obsidian", "stackable" => "1"), 
	array("id" => "50", "name" => "torch", "stackable" => "1"), 
#	array("id" => "51", "name" => "fire", "stackable" => "1"), 
	array("id" => "52", "name" => "monster spawner", "stackable" => "1"), 
	array("id" => "53", "name" => "wooden", "stackable" => "1"), 
	array("id" => "54", "name" => "chest", "stackable" => "1"), 
	array("id" => "55", "name" => "redstone wire", "stackable" => "1"), 
	array("id" => "56", "name" => "diamon ore", "stackable" => "1"), 
	array("id" => "57", "name" => "diamond block", "stackable" => "1"), 
	array("id" => "58", "name" => "workbench", "stackable" => "0"), 
	array("id" => "59", "name" => "crops", "stackable" => "1"), 
	array("id" => "60", "name" => "farmland", "stackable" => "1"), 
	array("id" => "61", "name" => "furnace", "stackable" => "1"), 
	array("id" => "62", "name" => "burning furnace", "stackable" => "1"), 
	array("id" => "63", "name" => "sign post", "stackable" => "1"), 
	array("id" => "64", "name" => "wooden door", "stackable" => "1"), 
	array("id" => "65", "name" => "ladder", "stackable" => "1"), 
	array("id" => "66", "name" => "minecart tracks", "stackable" => "1"), 
	array("id" => "67", "name" => "cobblestone stairs", "stackable" => "1"), 
	array("id" => "68", "name" => "wall sign", "stackable" => "1"), 
	array("id" => "69", "name" => "lever", "stackable" => "1"), 
	array("id" => "70", "name" => "stone pressure plate", "stackable" => "1"), 
	array("id" => "71", "name" => "iron door", "stackable" => "1"), 
	array("id" => "72", "name" => "wooden pressure plate", "stackable" => "1"), 
	array("id" => "73", "name" => "redstone ore", "stackable" => "1"), 
	array("id" => "74", "name" => "glowing redstone ore", "stackable" => "1"), 
#	array("id" => "75", "name" => "redstone torch off", "stackable" => "1"), 
	array("id" => "76", "name" => "redstone torch on", "stackable" => "1"), 
	array("id" => "77", "name" => "stone button", "stackable" => "1"), 
	array("id" => "78", "name" => "snow", "stackable" => "1"), 
	array("id" => "79", "name" => "ice", "stackable" => "1"), 
	array("id" => "80", "name" => "snow block", "stackable" => "1"), 
	array("id" => "81", "name" => "cactus", "stackable" => "1"), 
	array("id" => "82", "name" => "clay", "stackable" => "1"), 
	array("id" => "83", "name" => "sugar cane", "stackable" => "1"), 
	array("id" => "84", "name" => "jukebox", "stackable" => "1"), 
	array("id" => "85", "name" => "fence", "stackable" => "1"), 
	array("id" => "86", "name" => "pumpkin", "stackable" => "1"), 
	array("id" => "87", "name" => "netherrack", "stackable" => "1"), 
	array("id" => "88", "name" => "soul sand", "stackable" => "1"), 
	array("id" => "89", "name" => "glowstone", "stackable" => "1"), 
#	array("id" => "90", "name" => "portal", "stackable" => "1"), 
	array("id" => "91", "name" => "jack-o-lantern", "stackable" => "1"), 
	array("id" => "92", "name" => "cake block", "stackable" => "1"), 
#	array("id" => "93", "name" => "redstone repeater off", "stackable" => "1"), 
	array("id" => "94", "name" => "redstone repeater on", "stackable" => "1"), 
	array("id" => "95", "name" => "locked chest", "stackable" => "1"), 
	array("id" => "96", "name" => "trapdoor", "stackable" => "1"), 
	array("id" => "97", "name" => "hidden silverfish", "stackable" => "1"), 
	array("id" => "98", "name" => "stone bricks", "stackable" => "1"), 
	array("id" => "99", "name" => "huge brown mushroom", "stackable" => "1"), 
	array("id" => "100", "name" => "huge red mushroom", "stackable" => "1"), 
	array("id" => "101", "name" => "iron bars", "stackable" => "1"), 
	array("id" => "102", "name" => "glass plane", "stackable" => "1"), 
	array("id" => "103", "name" => "melon", "stackable" => "1"), 
	array("id" => "104", "name" => "pumpkin stem", "stackable" => "1"), 
	array("id" => "105", "name" => "melon stem", "stackable" => "1"), 
	array("id" => "106", "name" => "vines", "stackable" => "1"), 
	array("id" => "107", "name" => "fence gate", "stackable" => "1"), 
	array("id" => "108", "name" => "brick stairs", "stackable" => "1"), 
	array("id" => "109", "name" => "stone brick stairs", "stackable" => "1"), 
	array("id" => "110", "name" => "mycelium", "stackable" => "1"), 
	array("id" => "111", "name" => "lily pad", "stackable" => "1"), 
	array("id" => "112", "name" => "nether brick", "stackable" => "1"), 
	array("id" => "113", "name" => "nether brick fence", "stackable" => "1"), 
	array("id" => "114", "name" => "nether brick stairs", "stackable" => "1"), 
	array("id" => "115", "name" => "nether wart", "stackable" => "1"), 
	array("id" => "116", "name" => "enchantment table", "stackable" => "1"), 
	array("id" => "117", "name" => "brewing stand", "stackable" => "1"), 
	array("id" => "118", "name" => "cauldron", "stackable" => "1"), 
	array("id" => "119", "name" => "end portal", "stackable" => "1"), 
	array("id" => "120", "name" => "end portal frame", "stackable" => "1"), 
	array("id" => "121", "name" => "end stone", "stackable" => "1"), 
	array("id" => "122", "name" => "gdragon egg", "stackable" => "1"), 
#	array("id" => "123", "name" => "redstone lamp inactive", "stackable" => "1"), 
	array("id" => "124", "name" => "redstone lamp active", "stackable" => "1"), 
	array("id" => "256", "name" => "iron shovel", "stackable" => "1"), 
	array("id" => "257", "name" => "iron pickaxe", "stackable" => "1"), 
	array("id" => "258", "name" => "iron", "stackable" => "1"), 
	array("id" => "259", "name" => "flint and steel", "stackable" => "0"), 
	array("id" => "260", "name" => "apple", "stackable" => "1"), 
	array("id" => "261", "name" => "bow", "stackable" => "0"), 
	array("id" => "262", "name" => "arrow", "stackable" => "1"), 
	array("id" => "263", "name" => "coal", "stackable" => "1"), 
	array("id" => "264", "name" => "diamond", "stackable" => "1"), 
	array("id" => "265", "name" => "iron ingot", "stackable" => "1"), 
	array("id" => "266", "name" => "gold ingot", "stackable" => "1"), 
	array("id" => "267", "name" => "iron sword", "stackable" => "0"), 
	array("id" => "268", "name" => "wooden sword", "stackable" => "0"), 
	array("id" => "269", "name" => "wooden shovel", "stackable" => "0"), 
	array("id" => "270", "name" => "wooden pickaxe", "stackable" => "0"), 
	array("id" => "271", "name" => "wooden axe", "stackable" => "0"), 
	array("id" => "272", "name" => "stone sword", "stackable" => "0"), 
	array("id" => "273", "name" => "stone shovel", "stackable" => "0"), 
	array("id" => "274", "name" => "stone pickaxe", "stackable" => "0"), 
	array("id" => "275", "name" => "stone axe", "stackable" => "0"), 
	array("id" => "276", "name" => "diamond sword", "stackable" => "0"), 
	array("id" => "277", "name" => "diamond shovel", "stackable" => "0"), 
	array("id" => "278", "name" => "diamond pickaxe", "stackable" => "0"), 
	array("id" => "279", "name" => "diamond axe", "stackable" => "0"), 
	array("id" => "280", "name" => "stick", "stackable" => "1"), 
	array("id" => "281", "name" => "bowl", "stackable" => "1"), 
	array("id" => "282", "name" => "mushroom soup", "stackable" => "1"), 
	array("id" => "283", "name" => "gold sword", "stackable" => "0"), 
	array("id" => "284", "name" => "gold shovel", "stackable" => "0"), 
	array("id" => "285", "name" => "gold pickaxe", "stackable" => "0"), 
	array("id" => "286", "name" => "gold axe", "stackable" => "0"), 
	array("id" => "287", "name" => "string", "stackable" => "1"), 
	array("id" => "288", "name" => "feather", "stackable" => "1"), 
	array("id" => "289", "name" => "gunpowder", "stackable" => "1"), 
	array("id" => "290", "name" => "wooden hoe", "stackable" => "0"), 
	array("id" => "291", "name" => "stone hoe", "stackable" => "0"), 
	array("id" => "292", "name" => "iron hoe", "stackable" => "0"), 
	array("id" => "293", "name" => "diamond hoe", "stackable" => "0"), 
	array("id" => "294", "name" => "gold hoe", "stackable" => "0"), 
	array("id" => "295", "name" => "seeds", "stackable" => "1"), 
	array("id" => "296", "name" => "wheat", "stackable" => "1"), 
	array("id" => "297", "name" => "bread", "stackable" => "1"), 
	array("id" => "298", "name" => "leather helmet", "stackable" => "0"), 
	array("id" => "299", "name" => "leather chestplate", "stackable" => "0"), 
	array("id" => "300", "name" => "leather leggings", "stackable" => "0"), 
	array("id" => "301", "name" => "leather boots", "stackable" => "0"), 
	array("id" => "302", "name" => "chainmail helmet", "stackable" => "0"), 
	array("id" => "303", "name" => "chainmail chestplate", "stackable" => "0"), 
	array("id" => "304", "name" => "chainmail leggings", "stackable" => "0"), 
	array("id" => "305", "name" => "chainmail boots", "stackable" => "0"), 
	array("id" => "306", "name" => "iron helmet", "stackable" => "0"), 
	array("id" => "307", "name" => "iron chestplate", "stackable" => "0"), 
	array("id" => "308", "name" => "iron leggings", "stackable" => "0"), 
	array("id" => "309", "name" => "iron boots", "stackable" => "0"), 
	array("id" => "310", "name" => "diamond helmet", "stackable" => "0"), 
	array("id" => "311", "name" => "diamond chestplate", "stackable" => "0"), 
	array("id" => "312", "name" => "dimaond leggings", "stackable" => "0"), 
	array("id" => "313", "name" => "diamond boots", "stackable" => "0"), 
	array("id" => "314", "name" => "gold helmet", "stackable" => "0"), 
	array("id" => "315", "name" => "gold chestplate", "stackable" => "0"), 
	array("id" => "316", "name" => "gold leggings", "stackable" => "0"), 
	array("id" => "317", "name" => "gold boots", "stackable" => "0"), 
	array("id" => "318", "name" => "flint", "stackable" => "1"), 
	array("id" => "319", "name" => "raw porkchop", "stackable" => "1"), 
	array("id" => "320", "name" => "cooked porkchop", "stackable" => "1"), 
	array("id" => "321", "name" => "paintings", "stackable" => "0"), 
	array("id" => "322", "name" => "golden apple", "stackable" => "1"), 
	array("id" => "323", "name" => "sign", "stackable" => "0"), 
	array("id" => "324", "name" => "wooden door", "stackable" => "0"), 
	array("id" => "325", "name" => "bucket", "stackable" => "0"), 
	array("id" => "326", "name" => "water bucket", "stackable" => "0"), 
	array("id" => "327", "name" => "lava bucket", "stackable" => "0"), 
	array("id" => "328", "name" => "minecart", "stackable" => "0"), 
	array("id" => "329", "name" => "saddle", "stackable" => "0"), 
	array("id" => "330", "name" => "iron door", "stackable" => "0"), 
	array("id" => "331", "name" => "redstone", "stackable" => "1"), 
	array("id" => "332", "name" => "snowball", "stackable" => "1"), 
	array("id" => "333", "name" => "boat", "stackable" => "0"), 
	array("id" => "334", "name" => "leather", "stackable" => "1"), 
	array("id" => "335", "name" => "milk", "stackable" => "0"), 
	array("id" => "336", "name" => "clay brick", "stackable" => "1"), 
	array("id" => "337", "name" => "clay balls", "stackable" => "1"), 
	array("id" => "338", "name" => "sugar cane", "stackable" => "1"), 
	array("id" => "339", "name" => "paper", "stackable" => "1"), 
	array("id" => "340", "name" => "book", "stackable" => "1"), 
	array("id" => "341", "name" => "slimeball", "stackable" => "1"), 
	array("id" => "342", "name" => "storage minecart", "stackable" => "0"), 
	array("id" => "343", "name" => "powered minecart", "stackable" => "0"), 
	array("id" => "344", "name" => "egg", "stackable" => "1"), 
	array("id" => "345", "name" => "compass", "stackable" => "0"), 
	array("id" => "346", "name" => "fishing rod", "stackable" => "0"), 
	array("id" => "347", "name" => "clock", "stackable" => "0"), 
	array("id" => "348", "name" => "glowstone dust", "stackable" => "1"), 
	array("id" => "349", "name" => "raw fish", "stackable" => "1"), 
	array("id" => "350", "name" => "cooked fish", "stackable" => "1"), 
	array("id" => "351", "name" => "dye", "stackable" => "1"), 
	array("id" => "352", "name" => "bone", "stackable" => "1"), 
	array("id" => "353", "name" => "sugar", "stackable" => "1"), 
#	array("id" => "354", "name" => "cake", "stackable" => "1"), 
	array("id" => "355", "name" => "bed", "stackable" => "0"), 
	array("id" => "356", "name" => "redstone repeater", "stackable" => "1"), 
	array("id" => "357", "name" => "cookie", "stackable" => "1"), 
	array("id" => "358", "name" => "map", "stackable" => "0"), 
	array("id" => "359", "name" => "shears", "stackable" => "0"), 
	array("id" => "360", "name" => "melon slice", "stackable" => "1"), 
	array("id" => "361", "name" => "pumpkin seeds", "stackable" => "1"), 
	array("id" => "362", "name" => "melon seeds", "stackable" => "1"), 
	array("id" => "363", "name" => "raw beef", "stackable" => "1"), 
	array("id" => "364", "name" => "streak", "stackable" => "1"), 
	array("id" => "365", "name" => "raw chicken", "stackable" => "1"), 
	array("id" => "366", "name" => "cooked chicken", "stackable" => "1"), 
	array("id" => "367", "name" => "rotten flesh", "stackable" => "1"), 
	array("id" => "368", "name" => "ender pearl", "stackable" => "0"), 
	array("id" => "369", "name" => "blaze rod", "stackable" => "1"), 
	array("id" => "370", "name" => "ghast tear", "stackable" => "1"), 
	array("id" => "371", "name" => "gold nugget", "stackable" => "1"), 
	array("id" => "372", "name" => "nether wart", "stackable" => "1"), 
	array("id" => "373", "name" => "potions", "stackable" => "0"), 
	array("id" => "374", "name" => "glass bottle", "stackable" => "0"), 
	array("id" => "375", "name" => "spider eye", "stackable" => "1"), 
	array("id" => "376", "name" => "fermented spiter eye", "stackable" => "1"), 
	array("id" => "377", "name" => "blaze powder", "stackable" => "1"), 
	array("id" => "378", "name" => "magma cream", "stackable" => "1"), 
	array("id" => "379", "name" => "brewing stand", "stackable" => "0"), 
	array("id" => "380", "name" => "cauldron", "stackable" => "0"), 
	array("id" => "381", "name" => "eye of ender", "stackable" => "0"), 
	array("id" => "382", "name" => "glistering melon", "stackable" => "0"), 
	array("id" => "383", "name" => "spawn egg", "stackable" => "0"), 
	array("id" => "384", "name" => "bottle o' enchanting", "stackable" => "0"), 
	array("id" => "385", "name" => "fire charge", "stackable" => "0"), 
	array("id" => "2256", "name" => "gold disc", "stackable" => "0"), 
	array("id" => "2257", "name" => "green disk", "stackable" => "0"), 
	array("id" => "2258", "name" => "orange disk", "stackable" => "0"), 
	array("id" => "2259", "name" => "red disk", "stackable" => "0"), 
	array("id" => "2260", "name" => "lime green disk", "stackable" => "0"), 
	array("id" => "2261", "name" => "purple disk", "stackable" => "0"), 
	array("id" => "2262", "name" => "violet disk", "stackable" => "0"), 
	array("id" => "2263", "name" => "black disk", "stackable" => "0"), 
	array("id" => "2264", "name" => "white disk", "stackable" => "0"), 
	array("id" => "2265", "name" => "sea green disk", "stackable" => "0"), 
	array("id" => "2266", "name" => "broken disk", "stackable" => "0"), 
);


$scripts = array(
	"PENNEN!" => array(
	    "say PENNEN!",
		"say PENNEN!",
		"say USER möchte das ihr alle ins Bett geht", 
		"Say damit es wieder hell wird. Danke!"
	    ),
	"Diamant Werkzeug" => array(
	    "say USER drop Diamant Werkzeuge",
		"give USER 277 1", 
		"give USER 278 2", 
		"give USER 279 1"
	    ),
	"Starterkit" => array(
	    "say USER drop Starterkit",
		"give USER 278 1",
		"give USER 26 1",
		"give USER 345 1",
		"give USER 347 1",
		"give USER 346 1",
		"give USER 322 3"	
		),
	"Schienen Equipment" => array(
	    "say USER drop Schienen Equipment",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 27 64",
		"give USER 27 64",
		"give USER 27 64",
		"give USER 28 16",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 328 2",
		"give USER 76 64",
		"give USER 76 64"
		),
	"Elektro Equipment" => array(
	    "say USER drop Elektro Equipment",
		"give USER 76 64",
		"give USER 331 64",
		"give USER 77 64",
		"give USER 69 64",
		"give USER 42 64",
		"give USER 1 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 65 64",
		"give USER 76 64",
		"give USER 76 64",
		"give USER 75 64",
		"give USER 72 64",
		"give USER 71 64",
		"give USER 23 64",
		"give USER 42 64",
		"give USER 42 64",
		"give USER 93 64",
		"give USER 93 64",
		"give USER 63 64"
		),
    "Mining Equipment" => array(
        "say USER drop Mining Equipment",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 50 64",
		"give USER 50 64",
		"give USER 50 64",
		"give USER 50 64",
		"give USER 20 64",
		"give USER 20 64",
		"give USER 20 64",
		"give USER 20 64",
		"give USER 278 4",
		"give USER 277 2",
		"give USER 322 3",
		"give USER 326 1"
		),
	"Gartenbau Equipment" => array(
	    "say USER drop Gartenbau Equipment",
		"give USER 293 1",
		"give USER 2 64",
		"give USER 3 64",
		"give USER 352 64",
		"give USER 18 64",	
		"give USER 17 64",	
		"give USER 59 64",	
		"give USER 20 64",
		"give USER 40 64",
		"give USER 259 1",		
		"give USER 1 64",
		"give USER 6 64",
		"give USER 2 64",
		"give USER 2 64",
		"give USER 2 64",
		"give USER 352 64",
		"give USER 3 64",
		"give USER 3 64",
		"give USER 3 64",
		"give USER 50 64",
		"give USER 6 64",
		"give USER 6 64",
		"give USER 83 64",
	    "give USER 81 64",
		"give USER 30 64",
		"give USER 37 64",
		"give USER 38 64",
		"give USER 352 64",
		"give USER 352 64",
		"give USER 352 64",
		"give USER 85 64",			
		"give USER 8 64",
		"give USER 395 64",		
		"give USER 395 64",	
		"give USER 395 64",		
		"give USER 39 64",
		"give USER 12 64",
		"give USER 18 64"
		),
	"Give Sound Equipment" => array(
	    "say USER drop Sound Equipment",
		"give USER 25 64", 
		"give USER 25 64", 
		"give USER 25 64", 
		"give USER 331 64",
		"give USER 93 64",
		"give USER 2256 1",
		"give USER 2257 1", 
		"give USER 84 1", 
		"give USER 279 1",
		"give USER 277 1",
		"give USER 42 1",
		"give USER 42 1",
		"give USER 42 1",
        "give USER 76 64",	
        "give USER 76 64",
        "give USER 331 64",	
        "give USER 331 64",			
		"give USER 279 1"
	    ),
	"Robinhood Gear" => array(
	    "say USER drop Robinhood Gear",
		"give USER 298 1",
		"give USER 299 1",
		"give USER 300 1",
		"give USER 301 1",
		"give USER 261 1",
		"give USER 262 64",
		"give USER 262 64",
		"give USER 262 64",
		"give USER 262 64"
	    ),
	"Chainmail Warrior Gear" => array(
	    "say USER drop Chainmail Warrior Gear",
		"give USER 302 1",
		"give USER 303 1", 
		"give USER 304 1",
		"give USER 305 1",
		"give USER 267 1",
		"give USER 258 1", 
		"give USER 257 1", 
		"give USER 255 1"
		),
	"Gold Warrior Gear" => array(
	    "say USER drop Gold Warrior Gear",
		"give USER 314 1", 
		"give USER 315 1",
		"give USER 316 1", 
		"give USER 317 1", 
		"give USER 283 1",
		"give USER 284 1",
	    "give USER 285 1",
        "give USER 286 1"
		),
	"Diamond Warrior Gear" => array(
	    "say USER drop Diamond Warrior Gear",
		"give USER 310 1", 
		"give USER 311 1",
		"give USER 312 1", 
		"give USER 313 1", 
		"give USER 276 1"
	    ),
	#"Es werde Tag" => array(
	#    "say ..und USER sprach: Es werde Tag!",
	#    "say Warnung: Redstone Loop Schaltungen defekt!",
	#	"time set 0"
	#    ),
	#"Es werde Nacht" => array(
	#    "say ..und USER sprach: Es werde Nacht!",
	#    "say Warnung: Redstone Loop Schaltungen defekt!",
	#	"time set 20000"
	#    ),
		"TestScript" => array(
	    "tell yingpang w00p w00p - this is a test, initiated from USER",
		"tell escii w00p w00p - this is a test, initiated from USER"
	    ),
	    "Surprise" => array(
	    "say suprise suprise USER!",
		"give USER 357 1"
	    )
	   
	);


?>
