<?php

# settings:
$GLOBALS['maxitems'] = 2047;
$GLOBALS['nodejsServer'] = "http://localhost:8000";
$GLOBALS['versionString'] = "0.5";

$items = array(
        #sample	array("id" => "1", "name" => "nice stone", "stackable" => "1"),
        #sample	array("id" => "4", "name" => "gobble stone")

        array("id" => "1", "name" => "Einstein", "stackable" => "1"),
        array("id" => "2", "name" => "Weed", "stackable" => "1"),
        array("id" => "3", "name" => "Dirt", "stackable" => "1"),
        array("id" => "4", "name" => "Cobblestone", "stackable" => "1"),
        array("id" => "5", "name" => "Wooden Plank", "stackable" => "1"),
        array("id" => "6", "name" => "Sapling", "stackable" => "1"),
        array("id" => "8", "name" => "Flowing Water", "stackable" => "1"),
        array("id" => "9", "name" => "Solid Water", "stackable" => "1"),
        array("id" => "10", "name" => "Flowing Lava", "stackable" => "1"),
        array("id" => "11", "name" => "Solid Lava", "stackable" => "1"),
        array("id" => "12", "name" => "Sand", "stackable" => "1"),
        array("id" => "13", "name" => "Gravel", "stackable" => "1"),
        array("id" => "14", "name" => "Gold Ore", "stackable" => "1"),
        array("id" => "15", "name" => "Iron Ore", "stackable" => "1"),
        array("id" => "16", "name" => "Coal Ore", "stackable" => "1"),
        array("id" => "17", "name" => "Log", "stackable" => "1"),
        array("id" => "18", "name" => "Leaves", "stackable" => "1"),
        array("id" => "19", "name" => "Sponge", "stackable" => "1"),
        array("id" => "20", "name" => "Glass", "stackable" => "1"),
        array("id" => "21", "name" => "Lapis Lazuli Ore", "stackable" => "1"),
        array("id" => "22", "name" => "Lapis Lazuli Block", "stackable" => "1"),
        array("id" => "23", "name" => "Dispenser", "stackable" => "1"),
        array("id" => "24", "name" => "Sandstone", "stackable" => "1"),
        array("id" => "25", "name" => "Note Block", "stackable" => "1"),
 #       array("id" => "26", "name" => "Bed", "stackable" => "1"),
        array("id" => "27", "name" => "Powered Rail", "stackable" => "1"),
        array("id" => "28", "name" => "Detector Rail", "stackable" => "1"),
        array("id" => "29", "name" => "Sticky Piston", "stackable" => "1"),
        array("id" => "30", "name" => "Web", "stackable" => "1"),
        array("id" => "31", "name" => "Tall Grass", "stackable" => "1"),
        array("id" => "32", "name" => "Dead Shrub", "stackable" => "1"),
        array("id" => "33", "name" => "Piston", "stackable" => "1"),
        array("id" => "34", "name" => "Piston (Head)", "stackable" => "1"),
        array("id" => "35", "name" => "Wool", "stackable" => "1"),
        array("id" => "37", "name" => "Dandelion", "stackable" => "1"),
        array("id" => "38", "name" => "Rose", "stackable" => "1"),
        array("id" => "39", "name" => "Brown Mushroom", "stackable" => "1"),
        array("id" => "40", "name" => "Red Mushroom", "stackable" => "1"),
        array("id" => "41", "name" => "Gold Block", "stackable" => "1"),
        array("id" => "42", "name" => "Iron Block", "stackable" => "1"),
        array("id" => "43", "name" => "Double Stone Slab", "stackable" => "1"),
        array("id" => "44", "name" => "Stone Slab", "stackable" => "1"),
        array("id" => "45", "name" => "Brick", "stackable" => "1"),
        array("id" => "46", "name" => "TNT", "stackable" => "1"),
        array("id" => "47", "name" => "Bookcase", "stackable" => "1"),
        array("id" => "48", "name" => "Moss Stone", "stackable" => "1"),
        array("id" => "49", "name" => "Obsidian", "stackable" => "1"),
        array("id" => "50", "name" => "Torch", "stackable" => "1"),
    #    array("id" => "51", "name" => "Fire", "stackable" => "1"),
        #array("id" => "52", "name" => "Mob Spawner", "stackable" => "1"),
        array("id" => "53", "name" => "Wood Stairs", "stackable" => "1"),
        array("id" => "54", "name" => "Chest", "stackable" => "1"),
        array("id" => "56", "name" => "Diamond Ore", "stackable" => "1"),
        array("id" => "57", "name" => "Diamond Block", "stackable" => "1"),
        array("id" => "58", "name" => "Workbench", "stackable" => "0"),
        array("id" => "61", "name" => "Furnace", "stackable" => "1"),
        array("id" => "63", "name" => "Stackable Signs", "stackable" => "1"),
        array("id" => "64", "name" => "Stackable Wodden Door", "stackable" => "1"),
        array("id" => "65", "name" => "Ladder", "stackable" => "1"),
        array("id" => "66", "name" => "Rails", "stackable" => "1"),
        array("id" => "67", "name" => "Cobblestone Stairs", "stackable" => "1"),
        array("id" => "69", "name" => "Lever", "stackable" => "1"),
        array("id" => "70", "name" => "Stone Pressure Plate", "stackable" => "1"),
        array("id" => "72", "name" => "Wood Pressure Plate", "stackable" => "1"),
        array("id" => "73", "name" => "Redstone Ore", "stackable" => "1"),
        array("id" => "76", "name" => "Redstone Torch", "stackable" => "1"),
        array("id" => "77", "name" => "Stone Button", "stackable" => "1"),
        array("id" => "78", "name" => "Small Snow", "stackable" => "1"),
        array("id" => "79", "name" => "Ice", "stackable" => "1"),
        array("id" => "80", "name" => "Snow Block", "stackable" => "1"),
        array("id" => "81", "name" => "Cactus", "stackable" => "1"),
        array("id" => "82", "name" => "Clay Block", "stackable" => "1"),
        array("id" => "83", "name" => "Sugar Cane", "stackable" => "1"),
        array("id" => "84", "name" => "Jukebox", "stackable" => "1"),
        array("id" => "85", "name" => "Fence", "stackable" => "1"),
        array("id" => "86", "name" => "Pumpkin", "stackable" => "1"),
        array("id" => "87", "name" => "Netherrack", "stackable" => "1"),
        array("id" => "88", "name" => "Soul Sand", "stackable" => "1"),
        array("id" => "89", "name" => "Glowstone", "stackable" => "1"),
#        array("id" => "90", "name" => "Portal Piece", "stackable" => "1"),
        array("id" => "91", "name" => "Jack-O-Lantern", "stackable" => "1"),
        array("id" => "92", "name" => "Cake", "stackable" => "1"),
       # array("id" => "93", "name" => "Stackable Repeater", "stackable" => "1"),
        array("id" => "96", "name" => "Trapdoor", "stackable" => "1"),
#        array("id" => "256", "name" => "Iron Shovel", "stackable" => "1"),
#        array("id" => "257", "name" => "Iron Pickaxe", "stackable" => "1"),
#        array("id" => "258", "name" => "Iron Axe", "stackable" => "1"),
        array("id" => "259", "name" => "Flint and Steel", "stackable" => "0"),
        array("id" => "260", "name" => "Apple", "stackable" => "0"),
        array("id" => "261", "name" => "Bow", "stackable" => "0"),
        array("id" => "262", "name" => "Arrow", "stackable" => "1"),
        array("id" => "263", "name" => "Coal", "stackable" => "1"),
        array("id" => "264", "name" => "Diamond Gem", "stackable" => "1"),
        array("id" => "265", "name" => "Iron Ingot", "stackable" => "1"),
        array("id" => "266", "name" => "Gold Ingot", "stackable" => "1"),
#        array("id" => "267", "name" => "Iron Sword", "stackable" => "0"),
#        array("id" => "268", "name" => "Wood Sword", "stackable" => "0"),
#        array("id" => "269", "name" => "Wood Shovel", "stackable" => "0"),
#        array("id" => "270", "name" => "Wood Pickaxe", "stackable" => "0"),
#        array("id" => "271", "name" => "Wood Axe", "stackable" => "0"),
#        array("id" => "272", "name" => "Stone Sword", "stackable" => "0"),
#        array("id" => "273", "name" => "Stone Shovel", "stackable" => "0"),
#        array("id" => "274", "name" => "Stone Pickaxe", "stackable" => "0"),
#        array("id" => "275", "name" => "Stone Axe", "stackable" => "0"),
#        array("id" => "276", "name" => "Diamond Sword", "stackable" => "0"),
        array("id" => "277", "name" => "Diamond Shovel", "stackable" => "0"),
        array("id" => "278", "name" => "Diamond Pickaxe", "stackable" => "0"),
        array("id" => "279", "name" => "Diamond Axe", "stackable" => "0"),
        array("id" => "280", "name" => "Stick", "stackable" => "1"),
        array("id" => "281", "name" => "Bowl", "stackable" => "1"),
        array("id" => "282", "name" => "Mushroom Stew", "stackable" => "1"),
#        array("id" => "283", "name" => "Gold Sword", "stackable" => "1"),
#        array("id" => "284", "name" => "Gold Shovel", "stackable" => "1"),
#        array("id" => "285", "name" => "Gold Pickaxe", "stackable" => "1"),
#        array("id" => "286", "name" => "Gold Axe", "stackable" => "1"),
        array("id" => "287", "name" => "String", "stackable" => "1"),
        array("id" => "288", "name" => "Feather", "stackable" => "1"),
        array("id" => "289", "name" => "Gunpowder", "stackable" => "1"),
#        array("id" => "290", "name" => "Wood Hoe", "stackable" => "1"),
#        array("id" => "291", "name" => "Stone Hoe", "stackable" => "1"),
#        array("id" => "292", "name" => "Iron Hoe", "stackable" => "1"),
#        array("id" => "293", "name" => "Diamond Hoe", "stackable" => "1"),
#        array("id" => "294", "name" => "Gold Hoe", "stackable" => "1"),
        array("id" => "295", "name" => "Seeds", "stackable" => "1"),
        array("id" => "296", "name" => "Wheat", "stackable" => "1"),
        array("id" => "297", "name" => "Bread", "stackable" => "0"),
#        array("id" => "298", "name" => "Leather Helmet", "stackable" => "1"),
#        array("id" => "299", "name" => "Leather Chestplate", "stackable" => "1"),
#        array("id" => "300", "name" => "Leather Leggings", "stackable" => "1"),
#        array("id" => "301", "name" => "Leather Boots", "stackable" => "1"),
#        array("id" => "306", "name" => "Iron Helmet", "stackable" => "1"),
#        array("id" => "307", "name" => "Iron Chestplate", "stackable" => "1"),
#        array("id" => "308", "name" => "Iron Leggings", "stackable" => "1"),
#        array("id" => "309", "name" => "Iron Boots", "stackable" => "1"),
#        array("id" => "310", "name" => "Diamond Helmet", "stackable" => "1"),
#        array("id" => "311", "name" => "Diamond Chestplate", "stackable" => "1"),
#        array("id" => "312", "name" => "Diamond Leggings", "stackable" => "1"),
#        array("id" => "313", "name" => "Diamond Boots", "stackable" => "1"),
#        array("id" => "314", "name" => "Gold Helmet", "stackable" => "1"),
#        array("id" => "315", "name" => "Gold Chestplate", "stackable" => "1"),
#        array("id" => "316", "name" => "Gold Leggings", "stackable" => "1"),
#        array("id" => "317", "name" => "Gold Boots", "stackable" => "1"),
        array("id" => "318", "name" => "Flint", "stackable" => "1"),
        array("id" => "319", "name" => "Raw Porkchop", "stackable" => "0"),
        array("id" => "320", "name" => "Cooked Porkchop", "stackable" => "0"),
        array("id" => "321", "name" => "Painting", "stackable" => "1"),
        array("id" => "322", "name" => "Gold Apple", "stackable" => "0"),
        array("id" => "323", "name" => "Sign", "stackable" => "0"),
        array("id" => "324", "name" => "Wood Door", "stackable" => "0"),
        array("id" => "325", "name" => "Bucket", "stackable" => "0"),
        array("id" => "326", "name" => "Water Bucket", "stackable" => "0"),
        array("id" => "327", "name" => "Lava Bucket", "stackable" => "0"),
        array("id" => "328", "name" => "Minecart", "stackable" => "0"),
        array("id" => "329", "name" => "Saddle", "stackable" => "0"),
        array("id" => "330", "name" => "Iron Door", "stackable" => "0"),
        array("id" => "331", "name" => "Redstone Dust", "stackable" => "1"),
        array("id" => "332", "name" => "Snowball", "stackable" => "1"),
        array("id" => "333", "name" => "Boat", "stackable" => "0"),
        array("id" => "334", "name" => "Leather", "stackable" => "1"),
        array("id" => "335", "name" => "Milk", "stackable" => "0"),
        array("id" => "336", "name" => "Clay Brick", "stackable" => "1"),
#       array("id" => "337", "name" => "Clay", "stackable" => "1"),
        array("id" => "338", "name" => "Sugar Cane", "stackable" => "1"),
        array("id" => "339", "name" => "Paper", "stackable" => "1"),
        array("id" => "340", "name" => "Book", "stackable" => "1"),
        array("id" => "341", "name" => "Slime Ball", "stackable" => "1"),
        array("id" => "342", "name" => "Storage Minecart", "stackable" => "0"),
        array("id" => "343", "name" => "Powered Minecart", "stackable" => "0"),
        array("id" => "344", "name" => "Egg", "stackable" => "1"),
        array("id" => "345", "name" => "Compass", "stackable" => "0"),
        array("id" => "346", "name" => "Fishing Rod", "stackable" => "0"),
        array("id" => "347", "name" => "Watch", "stackable" => "0"),
        array("id" => "348", "name" => "Glowstone Dust", "stackable" => "1"),
        array("id" => "349", "name" => "Raw Fish", "stackable" => "0"),
        array("id" => "350", "name" => "Cooked Fish", "stackable" => "0"),
        array("id" => "351", "name" => "Ink Sack", "stackable" => "1"),
        array("id" => "352", "name" => "Bone", "stackable" => "1"),
        array("id" => "353", "name" => "Sugar", "stackable" => "1"),
#        array("id" => "354", "name" => "Cake", "stackable" => "1"),
        array("id" => "355", "name" => "Bed", "stackable" => "0"),
        array("id" => "356", "name" => "Redstone Repeater", "stackable" => "1"),
        array("id" => "357", "name" => "Cookie", "stackable" => "1"),
        array("id" => "358", "name" => "Map", "stackable" => "0"),
        array("id" => "359", "name" => "Shears", "stackable" => "0"),
        array("id" => "2256", "name" => "Gold Music Disk", "stackable" => "0"),
        array("id" => "2257", "name" => "Green Music Disk", "stackable" => "0")
);


$scripts = array(
	"PENNEN!" => array(
	    "say PENNEN!",
		"say PENNEN!",
		"say USER möchte das ihr alle ins Bett geht", 
		"Say damit es wieder hell wird. Danke!"
	    ),
	"Diamant Werkzeug" => array(
	    "say USER drop Diamant Werkzeuge",
		"give USER 277 1", 
		"give USER 278 2", 
		"give USER 279 1"
	    ),
	"Starterkit" => array(
	    "say USER drop Starterkit",
		"give USER 278 1",
		"give USER 26 1",
		"give USER 345 1",
		"give USER 347 1",
		"give USER 346 1",
		"give USER 322 3"	
		),
	"Schienen Equipment" => array(
	    "say USER drop Schienen Equipment",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 66 64",
		"give USER 27 64",
		"give USER 27 64",
		"give USER 27 64",
		"give USER 28 16",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 328 2",
		"give USER 76 64",
		"give USER 76 64"
		),
	"Elektro Equipment" => array(
	    "say USER drop Elektro Equipment",
		"give USER 76 64",
		"give USER 331 64",
		"give USER 77 64",
		"give USER 69 64",
		"give USER 42 64",
		"give USER 1 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 331 64",
		"give USER 65 64",
		"give USER 76 64",
		"give USER 76 64",
		"give USER 75 64",
		"give USER 72 64",
		"give USER 71 64",
		"give USER 23 64",
		"give USER 42 64",
		"give USER 42 64",
		"give USER 93 64",
		"give USER 93 64",
		"give USER 63 64"
		),
    "Mining Equipment" => array(
        "say USER drop Mining Equipment",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 1 64",
		"give USER 50 64",
		"give USER 50 64",
		"give USER 50 64",
		"give USER 50 64",
		"give USER 20 64",
		"give USER 20 64",
		"give USER 20 64",
		"give USER 20 64",
		"give USER 278 4",
		"give USER 277 2",
		"give USER 322 3",
		"give USER 326 1"
		),
	"Gartenbau Equipment" => array(
	    "say USER drop Gartenbau Equipment",
		"give USER 293 1",
		"give USER 2 64",
		"give USER 3 64",
		"give USER 352 64",
		"give USER 18 64",	
		"give USER 17 64",	
		"give USER 59 64",	
		"give USER 20 64",
		"give USER 40 64",
		"give USER 259 1",		
		"give USER 1 64",
		"give USER 6 64",
		"give USER 2 64",
		"give USER 2 64",
		"give USER 2 64",
		"give USER 352 64",
		"give USER 3 64",
		"give USER 3 64",
		"give USER 3 64",
		"give USER 50 64",
		"give USER 6 64",
		"give USER 6 64",
		"give USER 83 64",
	    "give USER 81 64",
		"give USER 30 64",
		"give USER 37 64",
		"give USER 38 64",
		"give USER 352 64",
		"give USER 352 64",
		"give USER 352 64",
		"give USER 85 64",			
		"give USER 8 64",
		"give USER 395 64",		
		"give USER 395 64",	
		"give USER 395 64",		
		"give USER 39 64",
		"give USER 12 64",
		"give USER 18 64"
		),
	"Give Sound Equipment" => array(
	    "say USER drop Sound Equipment",
		"give USER 25 64", 
		"give USER 25 64", 
		"give USER 25 64", 
		"give USER 331 64",
		"give USER 93 64",
		"give USER 2256 1",
		"give USER 2257 1", 
		"give USER 84 1", 
		"give USER 279 1",
		"give USER 277 1",
		"give USER 42 1",
		"give USER 42 1",
		"give USER 42 1",
        "give USER 76 64",	
        "give USER 76 64",
        "give USER 331 64",	
        "give USER 331 64",			
		"give USER 279 1"
	    ),
	"Robinhood Gear" => array(
	    "say USER drop Robinhood Gear",
		"give USER 298 1",
		"give USER 299 1",
		"give USER 300 1",
		"give USER 301 1",
		"give USER 261 1",
		"give USER 262 64",
		"give USER 262 64",
		"give USER 262 64",
		"give USER 262 64"
	    ),
	"Chainmail Warrior Gear" => array(
	    "say USER drop Chainmail Warrior Gear",
		"give USER 302 1",
		"give USER 303 1", 
		"give USER 304 1",
		"give USER 305 1",
		"give USER 267 1",
		"give USER 258 1", 
		"give USER 257 1", 
		"give USER 255 1"
		),
	"Gold Warrior Gear" => array(
	    "say USER drop Gold Warrior Gear",
		"give USER 314 1", 
		"give USER 315 1",
		"give USER 316 1", 
		"give USER 317 1", 
		"give USER 283 1",
		"give USER 284 1",
	    "give USER 285 1",
        "give USER 286 1"
		 
		),
	"Diamond Warrior Gear" => array(
	    "say USER drop Diamond Warrior Gear",
		"give USER 310 1", 
		"give USER 311 1",
		"give USER 312 1", 
		"give USER 313 1", 
		"give USER 276 1"
	    ),
	#"Es werde Tag" => array(
	#    "say ..und USER sprach: Es werde Tag!",
	#    "say Warnung: Redstone Loop Schaltungen defekt!",
	#	"time set 0"
	#    ),
	#"Es werde Nacht" => array(
	#    "say ..und USER sprach: Es werde Nacht!",
	#    "say Warnung: Redstone Loop Schaltungen defekt!",
	#	"time set 20000"
	#    ),
		"TestScript" => array(
	    "tell yingpang w00p w00p - this is a test, initiated from USER",
		"tell escii w00p w00p - this is a test, initiated from USER"
	    ),
	    "Surprise" => array(
	    "say suprise suprise USER!",
		"give USER 357 1"
	    )
	   
	);


?>
